services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: tiximax-tunnel
    restart: unless-stopped
    depends_on:
      - tiximax
    environment:
      TUNNEL_TRANSPORT_PROTOCOL: "http2"
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "--protocol"
      - "http2"
      - "--edge-ip-version"
      - "4"
      - "--ha-connections"
      - "2"
      - "--url"
      - "http://tiximax:10000"
